replicaCount: 1

image:
  repository: resume
  tag: dev
  pullPolicy: Never

service:
  type: NodePort
  port: 80
  nodePort: 30001

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi
