replicaCount: 1

image:
  repository: akspythonacr.azurecr.io/resume
  tag: dev
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30001

resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
